// Generated by IcedCoffeeScript 108.0.9
(function() {
  var GoEmitter, Main, avdl2json, emit, fs, iced, make_esc, minimist, output, pathmod, usage, __iced_k, __iced_k_noop;

  iced = require('iced-runtime');
  __iced_k = __iced_k_noop = function() {};

  minimist = require('minimist');

  avdl2json = require('avdl2json');

  GoEmitter = require('./emit').GoEmitter;

  make_esc = require('iced-error').make_esc;

  fs = require('fs');

  pathmod = require('path');

  usage = function() {
    return console.error("AVDL Compiler\n\n" + '  ' + "single file: avdlc -l <lang> -i <infile> -o <outfile>\n" + '  ' + "batch:       avdlc -l <lang> -b -o <outdir> <infiles...>\n\navdlc can run in either batch or single-file mode. Specify which language\nto output code in. Currently, only \"go\" is supported.");
  };

  emit = function(_arg, cb) {
    var code, e, json;
    json = _arg.json;
    e = new GoEmitter();
    code = e.run({
      json: json
    });
    return cb(null, code);
  };

  output = function(_arg, cb) {
    var code, err, outfile, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    outfile = _arg.outfile, code = _arg.code;
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced"
        });
        fs.writeFile(outfile, code.join("\n"), __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 30
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        return cb(err);
      };
    })(this));
  };

  exports.Main = Main = (function() {
    function Main() {}

    Main.prototype.parse_argv = function(_arg, cb) {
      var argv, err;
      argv = _arg.argv;
      argv = minimist(argv);
      if (argv.h) {
        usage();
        err = new Error("usage: shown!");
      } else if ((this.batch = argv.b)) {
        this.outdir = argv.o;
        this.infiles = argv._;
        if (!((this.outdir != null) && this.infiles.length)) {
          err = new Error("need an [-o <outdir>] and input files in batch mode");
        }
      } else {
        this.outfile = argv.o;
        this.infile = argv.i;
        if (!((this.outfile != null) && (this.infile != null))) {
          err = new Error("need an [-i <infile>] and a [-o <outfile>]");
        }
      }
      if ((argv.l == null) || argv.l !== "go") {
        err = new Error("must specify a language; candidates are: {'go'}");
      } else {
        this.lang = "go";
      }
      this.clean = argv.c;
      return cb(err);
    };

    Main.prototype.make_outfile = function(f) {
      return pathmod.join(this.outdir, (pathmod.basename(f, '.avdl')) + ".go");
    };

    Main.prototype.skip_infile = function(_arg, cb) {
      var err, esc, infile, outfile, s0, s1, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      infile = _arg.infile, outfile = _arg.outfile;
      esc = make_esc(cb, "skip_infile");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
            funcname: "Main.skip_infile"
          });
          fs.stat(infile, esc(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return s0 = arguments[0];
              };
            })(),
            lineno: 74
          })));
          fs.stat(outfile, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                err = arguments[0];
                return s1 = arguments[1];
              };
            })(),
            lineno: 75
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          return cb(null, !(typeof err !== "undefined" && err !== null) && (s0.mtime <= s1.mtime));
        };
      })(this));
    };

    Main.prototype.do_file = function(_arg, cb) {
      var ast, code, err, esc, infile, outfile, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      infile = _arg.infile, outfile = _arg.outfile;
      esc = make_esc(cb, "do_file");
      (function(_this) {
        return (function(__iced_k) {
          if (_this.clean) {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                funcname: "Main.do_file"
              });
              fs.unlink(outfile, __iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    return err = arguments[0];
                  };
                })(),
                lineno: 83
              }));
              __iced_deferrals._fulfill();
            })(function() {
              return __iced_k(typeof err === "undefined" || err === null ? console.log("Deleting " + outfile) : void 0);
            });
          } else {
            (function(__iced_k) {
              __iced_deferrals = new iced.Deferrals(__iced_k, {
                parent: ___iced_passed_deferral,
                filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                funcname: "Main.do_file"
              });
              avdl2json.parse({
                infile: infile,
                version: 2
              }, esc(__iced_deferrals.defer({
                assign_fn: (function() {
                  return function() {
                    return ast = arguments[0];
                  };
                })(),
                lineno: 86
              })));
              __iced_deferrals._fulfill();
            })(function() {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                  funcname: "Main.do_file"
                });
                emit({
                  json: ast.to_json()
                }, esc(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return code = arguments[0];
                    };
                  })(),
                  lineno: 87
                })));
                __iced_deferrals._fulfill();
              })(function() {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                    funcname: "Main.do_file"
                  });
                  output({
                    code: code,
                    outfile: outfile
                  }, esc(__iced_deferrals.defer({
                    lineno: 88
                  })));
                  __iced_deferrals._fulfill();
                })(function() {
                  return __iced_k(console.log("Compiling " + infile + " -> " + outfile));
                });
              });
            });
          }
        });
      })(this)((function(_this) {
        return function() {
          return cb(null);
        };
      })(this));
    };

    Main.prototype.do_batch_mode = function(opts, cb) {
      var esc, infile, outfile, skip, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      esc = make_esc(cb, "do_batch_mode");
      (function(_this) {
        return (function(__iced_k) {
          var _i, _len, _ref, _results, _while;
          _ref = _this.infiles;
          _len = _ref.length;
          _i = 0;
          _while = function(__iced_k) {
            var _break, _continue, _next;
            _break = __iced_k;
            _continue = function() {
              return iced.trampoline(function() {
                ++_i;
                return _while(__iced_k);
              });
            };
            _next = _continue;
            if (!(_i < _len)) {
              return _break();
            } else {
              infile = _ref[_i];
              outfile = _this.make_outfile(infile);
              skip = false;
              (function(__iced_k) {
                if (!_this.clean) {
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                      funcname: "Main.do_batch_mode"
                    });
                    _this.skip_infile({
                      infile: infile,
                      outfile: outfile
                    }, esc(__iced_deferrals.defer({
                      assign_fn: (function() {
                        return function() {
                          return skip = arguments[0];
                        };
                      })(),
                      lineno: 100
                    })));
                    __iced_deferrals._fulfill();
                  })(__iced_k);
                } else {
                  return __iced_k();
                }
              })(function() {
                (function(__iced_k) {
                  if (!skip) {
                    (function(__iced_k) {
                      __iced_deferrals = new iced.Deferrals(__iced_k, {
                        parent: ___iced_passed_deferral,
                        filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                        funcname: "Main.do_batch_mode"
                      });
                      _this.do_file({
                        infile: infile,
                        outfile: outfile
                      }, esc(__iced_deferrals.defer({
                        lineno: 102
                      })));
                      __iced_deferrals._fulfill();
                    })(__iced_k);
                  } else {
                    return __iced_k();
                  }
                })(_next);
              });
            }
          };
          _while(__iced_k);
        });
      })(this)((function(_this) {
        return function() {
          return cb(null);
        };
      })(this));
    };

    Main.prototype.main = function(_arg, cb) {
      var argv, esc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      argv = _arg.argv;
      esc = make_esc(cb, "main");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
            funcname: "Main.main"
          });
          _this.parse_argv({
            argv: argv
          }, esc(__iced_deferrals.defer({
            lineno: 109
          })));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          (function(__iced_k) {
            if (_this.batch) {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                  funcname: "Main.main"
                });
                _this.do_batch_mode({}, esc(__iced_deferrals.defer({
                  lineno: 111
                })));
                __iced_deferrals._fulfill();
              })(__iced_k);
            } else {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
                  funcname: "Main.main"
                });
                _this.do_file({
                  infile: _this.infile,
                  outfile: _this.outfile
                }, esc(__iced_deferrals.defer({
                  lineno: 113
                })));
                __iced_deferrals._fulfill();
              })(__iced_k);
            }
          })(function() {
            return cb(null);
          });
        };
      })(this));
    };

    return Main;

  })();

  exports.main = function() {
    var err, main, rc, ___iced_passed_deferral, __iced_deferrals, __iced_k;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    main = new Main;
    (function(_this) {
      return (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "/Users/max/src/keybase/node-avdl-compiler/src/main.iced",
          funcname: "main"
        });
        main.main({
          argv: process.argv.slice(2)
        }, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return err = arguments[0];
            };
          })(),
          lineno: 120
        }));
        __iced_deferrals._fulfill();
      });
    })(this)((function(_this) {
      return function() {
        rc = 0;
        if (typeof err !== "undefined" && err !== null) {
          rc = -2;
          console.error(err.toString().red);
        }
        return process.exit(rc);
      };
    })(this));
  };

}).call(this);
