// Generated by IcedCoffeeScript 108.0.11
(function() {
  var is_primitive;

  is_primitive = function(type) {
    var first_char;
    first_char = type.charAt(0);
    return first_char === first_char.toLowerCase() && first_char !== first_char.toUpperCase();
  };

  module.exports = {
    is_primitive: is_primitive
  };

}).call(this);
